"""
Back-fill HMRC manual citations into rule YAML files.

Reads citation_map.json (generated by tag_rules.py) and for each rule YAML
that is missing a citation for a manual section that references it, adds the
citation automatically.

This script is run after indexing so that rule YAMLs stay in sync with the
HMRC chunks that have been indexed.  It writes changes back to disk; in CI the
result is committed to the repository via git-auto-commit-action.

Usage:
    python sync_citations.py [--citation-map scripts/indexing/citation_map.json]
                             [--rules-dir src/hmrc_tax_mcp/registry/rules]
                             [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml

RULES_DIR = Path("src/hmrc_tax_mcp/registry/rules")
CITATION_MAP = Path("scripts/indexing/citation_map.json")

# Base URLs for known manuals — used to construct citation URLs
MANUAL_URLS: dict[str, str] = {
    "PTM":   "https://www.gov.uk/hmrc-internal-manuals/pensions-tax-manual",
    "IHTM":  "https://www.gov.uk/hmrc-internal-manuals/inheritance-tax-manual",
    "CG":    "https://www.gov.uk/hmrc-internal-manuals/capital-gains-manual",
    "PIM":   "https://www.gov.uk/hmrc-internal-manuals/property-income-manual",
    "EIM":   "https://www.gov.uk/hmrc-internal-manuals/employment-income-manual",
    "HS":    "https://www.gov.uk/government/publications",
}

REF_PREFIX = re.compile(r"^([A-Z]{2,6})")


def ref_to_url(ref: str) -> str:
    """Build a Gov.uk URL for a manual section reference."""
    match = REF_PREFIX.match(ref)
    prefix = match.group(1) if match else ""
    base = MANUAL_URLS.get(prefix, "https://www.gov.uk/hmrc-internal-manuals")
    return f"{base}/{ref.lower()}"


def load_citation_map(path: Path) -> dict[str, list[str]]:
    return json.loads(path.read_text())


def load_rule_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text())


def dump_rule_yaml(data: dict, path: Path) -> None:
    """Write a rule dict back to YAML, preserving key order."""
    path.write_text(
        yaml.dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False)
    )


def existing_refs(rule: dict) -> set[str]:
    """Return the set of manual section refs already in the rule's citations."""
    refs: set[str] = set()
    for citation in rule.get("citations", []):
        if isinstance(citation, dict):
            refs.add(citation.get("label", ""))
        elif isinstance(citation, str):
            refs.add(citation)
    return refs


def sync_rule(rule_path: Path, refs_to_add: list[str], dry_run: bool) -> bool:
    """Add missing citations to one rule YAML.  Returns True if changed."""
    rule = load_rule_yaml(rule_path)
    current_refs = existing_refs(rule)

    new_citations = [
        {"label": ref, "url": ref_to_url(ref)}
        for ref in refs_to_add
        if ref not in current_refs
    ]

    if not new_citations:
        return False

    rule.setdefault("citations", []).extend(new_citations)

    if dry_run:
        for c in new_citations:
            print(f"  [dry-run] would add {c['label']} to {rule_path}")
        return True

    dump_rule_yaml(rule, rule_path)
    for c in new_citations:
        print(f"  Added {c['label']} to {rule_path.name}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--citation-map",
        type=Path,
        default=CITATION_MAP,
        help="Path to citation_map.json",
    )
    parser.add_argument(
        "--rules-dir",
        type=Path,
        default=RULES_DIR,
        help="Root of the rules directory",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print changes without writing to disk",
    )
    args = parser.parse_args()

    if not args.citation_map.exists():
        raise FileNotFoundError(
            f"citation_map.json not found at {args.citation_map}. "
            "Run tag_rules.py first."
        )

    citation_map = load_citation_map(args.citation_map)

    # Build reverse map: rule_id → [manual_refs]
    rule_to_refs: dict[str, list[str]] = {}
    for ref, rule_ids in citation_map.items():
        for rule_id in rule_ids:
            rule_to_refs.setdefault(rule_id, []).append(ref)

    changed = 0
    skipped = 0

    # Walk all tax-year directories and update every matching rule YAML
    for year_dir in sorted(args.rules_dir.iterdir()):
        if not year_dir.is_dir():
            continue
        for yaml_path in sorted(year_dir.rglob("*.yaml")):
            rule = load_rule_yaml(yaml_path)
            rule_id = rule.get("rule_id")
            if not rule_id:
                continue

            # Strip tax-year suffix if present (e.g. pension_annual_allowance.2025-26)
            base_id = rule_id.split(".")[0]
            refs = rule_to_refs.get(base_id) or rule_to_refs.get(rule_id, [])

            if not refs:
                skipped += 1
                continue

            if sync_rule(yaml_path, refs, dry_run=args.dry_run):
                changed += 1

    print(
        f"\nDone. {'Would update' if args.dry_run else 'Updated'} {changed} rule YAMLs "
        f"({skipped} had no indexed citations)."
    )


if __name__ == "__main__":
    main()
